### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by JurRutten** [fab2s/NodalFlow#8]
Are there any plans to make this package Symfony 5 compatible?
It seems there is some work concerning the changed signature of EventDispatcherInterface::dispatch

Is this package still mantained?

**Comment by fab2s** [comment]
OMG, they really need to make up their mind with such a low level interface, I really have hard time to think about any reason why they would move it so much.

I will provide with a patch shortly (and yes this package is maintained, v2 is on its way). On the good part, it should not cause any perf issue after I had to already handle such changes with signature.

**Comment by fab2s** [comment]
So in the end, symfony 5 added some extra work to preserve BC. I have a PR ready for 2.x branch, which version where you using ?

I'm not convinced this required any back port due to the minimum php version involved.

**Comment by JurRutten** [comment]
I'm using fab2s/yaetl 1.1.1 that uses fab2s/NodalFlow 1.1.2
I'm willing to upgrade/migrate if there is a 2.* tag of both 😀

Thanks a lot 👍

**Comment by fab2s** [comment]
I just pushed a commit to Yaetl 2.x-dev branch, should be pretty close to stable now.

I will do a thorough review and decide myself if I should release or wait for the new feature I was thinking about before that (long awaited HTTP extractor).

**Comment by JurRutten** [comment]
Any news on a more definitive version/release?
Thanks again for the effort 👍
